header:
  version: 14

local_conf_header:
  hash_equivalicen: |
    # Enable support for automatically running a local hash equivalence server and
    # instruct bitbake to use a hash equivalence aware signature generator. Hash
    # equivalence improves reuse of sstate by detecting when a given sstate
    # artifact can be reused as equivalent, even if the current task hash doesn't
    # match the one that generated the artifact.
    #
    # A shared hash equivalent server can be set with "<HOSTNAME>:<PORT>" format
    #
    #BB_HASHSERVE = "auto"
    #BB_SIGNATURE_HANDLER = "OEEquivHash"

  memory_resident_bitbake: |
    # Bitbake's server component can stay in memory after the UI for the current command
    # has completed. This means subsequent commands can run faster since there is no need
    # for bitbake to reload cache files and so on. Number is in seconds, after which the
    # server will shut down.
    #
    #BB_SERVER_TIMEOUT = "60"

  multithread_build: |
    # As recommended by https://www.yoctoproject.org/docs/latest/mega-manual/mega-manual.html#var-BB_NUMBER_THREADS
    # and https://www.yoctoproject.org/docs/latest/mega-manual/mega-manual.html#var-PARALLEL_MAKE:
    BB_NUMBER_THREADS ?= "${@min(int(bb.utils.cpu_count()), 20)}"
    PARALLEL_MAKE ?= "-j ${BB_NUMBER_THREADS}"