header:
  version: 14

local_conf_header:
  package_management_configuration: |
    # This variable lists which packaging formats to enable. Multiple package backends
    # can be enabled at once and the first item listed in the variable will be used
    # to generate the root filesystems.
    # Options are:
    #  - 'package_deb' for debian style deb files
    #  - 'package_ipk' for ipk files are used by opkg (a debian style embedded package manager)
    #  - 'package_rpm' for rpm style packages
    # E.g.: PACKAGE_CLASSES ?= "package_rpm package_deb package_ipk"
    # We default to ipk:
    PACKAGE_CLASSES ?= "package_deb"
    #
    # Include the package management utilities in the image ("opkg", by default)
    EXTRA_IMAGE_FEATURES += "package-management"
